kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'default:privileged'
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:masters'
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:nodes'
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccounts:kube-system'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'psp:privileged'
